---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    #image: quay.io/centos/centos:7
    image: docker.io/centos:centos7
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible

